### ISSUE TITLE
feature request: changing colors of index view

### ISSUE THREAD

**Issue by Radvendii** [astroidmail/astroid#219]
I posted this to the forum, but that seems to get little to no attention. I guess this is the right place to post it?

Is there a way to configure astroid to be white-on-black? Or in general to customize colorscheme?
I've found the css file to customize the thread view, but nothing for index view. (and the css file is not the most convenient for this)
I was thinking of adding this feature, but I wanted to make sure that it didn't already exist first.

**Comment by gauteh** [comment]
Radvendii writes on september 15, 2016 15:24:
> I posted this to the forum, but that seems to get little to no attention. I guess this is the right place to post it?
> 
> Is there a way to configure astroid to be white-on-black? Or in general to customize colorscheme?
> I've found the css file to customize the thread view, but nothing for index view. (and the css file is not the most convenient for this)
> I was thinking of adding this feature, but I wanted to make sure that it didn't already exist first.
> 

The thread-index gets its colors from the GTK theme, so you could make
a custom GTK theme for that. In addition to that it is currently
possible to customize the colors of the tag list using a plugin [0],
though none of the other fields yet - that would be nice though.

I also want to implement a bigger thread-index line, so that the current
compact and a bigger view could be toggeled. Especially with lots of
tags its just not enough space on one line.

**Comment by gauteh** [comment]
Closing for now, you can change Gtk theme.
