### ISSUE TITLE
Tab wrapping-behaviour different in thread index

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#225]
while

  thread_index.next_unread=Key (GDK_KEY_Tab) # Jump to next unread thread

wraps,

  thread_index.previous_unread=Key (false, false, (guint) GDK_KEY_ISO_Left_Tab) # Jump to previous unread thread

does not wrap

**Comment by mxmehl** [comment]
I can reproduce the issue after we clarified what is meant by "wrapping".

In ThreadIndex more than one unread thread, you can cycle through the unread threads: Tab towards the bottom, Shift-Tab towards the top. At the very top, S-Tab doesn't jump to the very bottom. However the other way round, Tab will make the focus jump from the oldest unread thread to the newest.

The expected behaviour is that S-Tab also allows the user to cycle to the opposite end.

**Comment by gauteh** [comment]
So with:
```
thread 0: read
thread 1: read
thread 2: unread
thread 3: read        <- current focus
thread 4 : unread
thread 5 read
```
you press: `Shift-Tab` thread 2 will be focused, if you press again thread 4 will _not_ be focused? (this works for me)

**Comment by gauteh** [comment]
Please test latest master, seems to have been a bug when the first thread in the index was unread.
