### ISSUE TITLE
External updates to the notmuch db

### ISSUE THREAD

**Issue by ldegen** [astroidmail/astroid#276]
Hi, just a question:

In my current mail setup, offlineimap and notmuch are triggered from a cron job. 
Is it possible to make astroid refresh its views using a notmuch hook or something?
Or would it make sense to run notmuch (but not offlineimap) in astroids poll script?
#265 seems to suggest that this would trigger an update?
Sorry, if this sounds confused. I am a bit confused :-)

**Comment by gauteh** [comment]
ldegen writes on februar 14, 2017 19:07:
> Hi, just a question:
> 
> In my current mail setup, offlineimap and notmuch are triggered from a cron job. 
> Is it possible to make astroid refresh its views using a notmuch hook or something?
> Or would it make sense to run notmuch (but not offlineimap) in astroids poll script?
> #265 seems to suggest that this would trigger an update?
> Sorry, if this sounds confused. I am a bit confused :-)
> 

At this point automatic refresh can only be achieved by using astroids
regular polling, you can configure something that is similar to what you
have (albeit only when astroid is running) by setting up a poll
interval, and a poll script which does the same as your crontab command
does now.

More information here: https://github.com/astroidmail/astroid/wiki/Polling

After poll.sh is run and returns with a successful exit status all the
threads that have changed since before the poll was run are updated.

At the moment the above described is the recommended setup, if this is
not possible a feature could possibly be implemented where astroid with
a command line option triggers a refresh, as an argument a notmuch
database revision needs to be given so that only the changed threads are
updated in the GUI. This revision must be tracked by the triggering mechanism.

**Comment by ldegen** [comment]
Ah, thanks for explaining. 

I tried using a poll.sh that only runs `notmuch new`. 
Which unsurprisingly reports "No new mail" (because my cron job did just run the same a couple of seconds ago).

In such a  case, will astroid still pick up the changes that occurred since its last poll? To me it seems, as if there is some kind of race going on. Sometimes I do not see new mails until I refresh using '$'. At other times, it just works.

For now, I will change my cron job to abort early if it detects astroid is running. That should do as a work-around. 

About externally triggering a refresh via the CLI: Yes, maybe a solution. I would do this in a notmuch hook, I suppose? So no matter who or what calls `notmuch new`, astroid gets refreshed?

**Comment by gauteh** [comment]
ldegen writes on februar 15, 2017 10:06:
> Ah, thanks for explaining. 
> 
> I tried using a poll.sh that only runs `notmuch new`. 
> Which unsurprisingly reports "No new mail" (because my cron job did just run the same a couple of seconds ago).
>
> 
> In such a  case, will astroid still pick up the changes that occurred since its last poll? To me it seems, as if there is some kind of race going on. Sometimes I do not see new mails until I refresh using '$'. At other times, it just works.

If it only runs notmuch new it will only check messages that changed
since before the poll script starts and ends, which if your sync
operation completed before wont be anything. `notmuch new` returning 'No
new mail' means that this happened, and nothing will get updated in
astroid. You would have to do the synchronization (offlineimap + notmuch
new) there, and only there, for it to work.
 
> For now, I will change my cron job to abort early if it detects astroid is running. That should do as a work-around. 

Yes, that could work, and then you do both: offlineimap + notmuch new in
the poll script.

> 
> About externally triggering a refresh via the CLI: Yes, maybe a solution. I would do this in a notmuch hook, I suppose? So no matter who or what calls `notmuch new`, astroid gets refreshed?
> 

We would have to make sure that no astroid instance is started if it is not
already running in that case.

By the way, notifymuch might be useful in your case.

**Comment by ldegen** [comment]
Ok, got it working :-). Thanks again.

**Comment by gauteh** [comment]
Good :)
