### ISSUE TITLE
How to get IMAP mail instantly 

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#302]
Currently the way we suggest to fetch email with astroid is to go through astroid's polling script and rely on offlineimap.

One of the drawback of this solution is that astroid only fetches new mail and update the notmuch database every X minutes or so.  Therefore, the user does not get new mail instantly in his/her INBOX even though the IMAP server already has it.

I do not suggest moving astroid into an IMAP client as such (e.g. mutt has this capability). 

Maybe there's an easy way to do this with offlineimap; but I suppose that requires having the poll script run once at startup only to launch offlineimap as a deamon (and then use offlineimap post sync hook to launch the notmuch new and other scripts).

(Related to #64 - cc @taziden)

Ideas? Config suggestions, or Howtos that we can point to from the wiki?

**Comment by hugoroy** [comment]
One quick workaround: have a very small "poll.interval" value and include some way in poll.sh to check of everything's fine in offineimap (check that there are no ".lock" files made by offlineimap and if there are, then make a notification to the desktop that offlineimap is having issues).

**Comment by gauteh** [comment]
Yes, I would like to see this as well. And I have been pondering how
to do this, one simple approach is perhaps something like this:

``` 
offlineimap.pre-sync:
astroid --start-polling
```

this tells astroid that there is a polling action going on, it will
start the spinner and treat the DB as R/W lock.

If there is some pid to watch we could even also monitor this, but I
think different syncing programs behave differently in this regard.

then in:
```
offlineimap.post-sync:
notmuch new
astroid --stop-polling
```

which tells astroid that the DB is free, and we will look for updates
since the --start-poll call. This should make it possible to run
offlineimap in the background. We could also make a time-out on the
polling action, but this opens us up to the #64 bug.

Implementing these two options should be fairly trivial in the current
design.

I think the best would be for the user to manually launch offlineimap
outside astorid and disable the internal polling in this case. If need
be you could wrap astroid in a small shell script that starts or stops
the offlineimap daemon.

If it were possible for offlineimap to output which files where
changed to the post-sync hook it would make it much easier to check for
external tag changes in abunchoftags [0], but that is a bit off-topic.
Do you know if this is possible?

[0] https://github.com/gauteh/abunchoftags

(ping @moddx / #275)

-gaute

**Comment by gauteh** [comment]
#303 implements these options. You might still have issues, because I currently don't lock the DB in polling as I first though. This would probably cause a lot of unnecessary hang-ups in the UI while waiting for the imap operations to complete (which don't need notmuch db locks). That particualar issue looks like it will be fixed in notmuch though.

**Comment by gauteh** [comment]
If you use an IMAP syncer which IDLE or perhaps use something like https://github.com/rakoo/idlewatch to trigger syncs that might give you more instant syncs.

**Comment by gauteh** [comment]
I also used this script with limited success with Gmail to quickly check if I needed to sync: https://gist.github.com/gauteh/7942217

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 4, 2017 23:42:
> If you use an IMAP syncer which IDLE or perhaps use something like https://github.com/rakoo/idlewatch to trigger syncs that might give you more instant syncs.


Offlineimap has IDLE support. But it does not seem to work for us.


There's this in the offlineimap config example:

    # This option stands in the [Repository RemoteExample] section.
    #
    # In between synchronisations, Offlineimap can monitor mailboxes for new
    # messages using the IDLE command. If you want to enable this, specify here the
    # folders you wish to monitor. IMAP protocol requires a separate connection for
    # each folder monitored in this way, so setting this option will force settings
    # for:
    #
    #  - maxconnections: to be at least the number of folders you give
    #  - holdconnectionopen: to be true
    #  - keepalive: to be 29 minutes unless you specify otherwise
    #  - singlethreadperfolder: to be true
    #
    # The presynchook and postsynchook are executed for each new synchronisation per
    # folder.
    #
    # This feature isn't complete and may well have problems. See the "Known Issues"
    # entry in the manual for more details.
    #
    # This option should return a Python list. For example
    #
    #idlefolders = ['INBOX', 'INBOX.Alerts']


But then, it says this in the "Known Issues" in the manual:


       ·   IDLE support is incomplete and experimental. Bugs may be encountered.

           ·   No hook exists for "run after an IDLE response".

               Email will show up, but may not be processed until the next refresh cycle.

           ·   nametrans may not be supported correctly.

           ·   IMAP IDLE <→ IMAP IDLE doesn’t work yet.

           ·   IDLE might stop syncing on a system suspend/resume.

           ·   IDLE may only work "once" per refresh.

               If you encounter this bug, please send a report to the list!


Obviously, the fact that there's no hook made after an IDLE response is
a major dealbreaker.

**Comment by gauteh** [comment]
Hugo Roy writes on mars 5, 2017 12:29:
> ↪ Gaute Hope / mars 4, 2017 23:42:
>> If you use an IMAP syncer which IDLE or perhaps use something like https://github.com/rakoo/idlewatch to trigger syncs that might give you more instant syncs.
> 
> 
> Offlineimap has IDLE support. But it does not seem to work for us.

That is too bad. I always have trouble finding proper offlineimap
documentation. It seems that the new thing is imapfw [0], but I don't know
how ready that is.. are there other alternatives (mbsync [1])?

I am currently stuck with offlineimap since it is the only one that can
sync X-Keywords with gmail that I am aware of [2].

IMAP syncers:

[0] imapfw: https://github.com/OfflineIMAP/imapfw
[1] mbsync (isync): http://isync.sourceforge.net/mbsync.html

[2] offlinemap, gmail: https://github.com/OfflineIMAP/offlineimap/commit/0e4afa913253c43409e6a32a6b6e11e8b03ed3d9 (orignal docs gone..?)

- gaute

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 5, 2017 15:08:
> [1] mbsync (isync): http://isync.sourceforge.net/mbsync.html

I tried that one, the experience was *awful*. The UI is absolutely not
clear and it seems overly complex. I tried it for a week or so and went
back to offlineimap.

**Comment by gauteh** [comment]
You can also use `offlineimap -q` with higher number of `maxconnections` to get faster syncs. Together with https://github.com/gauteh/gmailieer and two IMAP accounts it takes me about 4 seconds to do a poll.

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 8, 2017 17:19:
> You can also use `offlineimap -q` with higher number of `maxconnections` to get faster syncs. Together with https://github.com/gauteh/gmailieer and two IMAP accounts it takes me about 4 seconds to do a poll.

But isn't it good once in a while to run a real sync and not just a
quick sync?

Maybe the poll.sh sample could increment the quick sync and after, n
sync run a normal non quick sync. Does that look like a good idea? Even
I could do that in bash I guess ;^)

**Comment by gauteh** [comment]
Hugo Roy writes on mars 9, 2017 8:51:
> ↪ Gaute Hope / mars 8, 2017 17:19:
>> You can also use `offlineimap -q` with higher number of `maxconnections` to get faster syncs. Together with https://github.com/gauteh/gmailieer and two IMAP accounts it takes me about 4 seconds to do a poll.
> 
> But isn't it good once in a while to run a real sync and not just a
> quick sync?
> 
> Maybe the poll.sh sample could increment the quick sync and after, n
> sync run a normal non quick sync. Does that look like a good idea? Even
> I could do that in bash I guess ;^)

Hey! I just added a small section on that in the wiki: https://github.com/astroidmail/astroid/wiki/Advanced-Polling-and-Processing-mail#advanced-polling

Could you have a look if that makes sense, please edit if it is unclear.

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 9, 2017 8:52:
> Hugo Roy writes on mars 9, 2017 8:51:
>> ↪ Gaute Hope / mars 8, 2017 17:19:
>>> You can also use `offlineimap -q` with higher number of `maxconnections` to get faster syncs. Together with https://github.com/gauteh/gmailieer and two IMAP accounts it takes me about 4 seconds to do a poll.
>> 
>> But isn't it good once in a while to run a real sync and not just a
>> quick sync?
>> 
>> Maybe the poll.sh sample could increment the quick sync and after, n
>> sync run a normal non quick sync. Does that look like a good idea? Even
>> I could do that in bash I guess ;^)
> 
> Hey! I just added a small section on that in the wiki: https://github.com/astroidmail/astroid/wiki/Advanced-Polling-and-Processing-mail#advanced-polling
> 
> Could you have a look if that makes sense, please edit if it is unclear.

Your plan is to ruin by bash skills, isn't it? :)

It is very clear. Testing now :-)

**Comment by gauteh** [comment]
Hugo Roy writes on mars 9, 2017 9:01:
> ↪ Gaute Hope / mars 9, 2017 8:52:
>> Hugo Roy writes on mars 9, 2017 8:51:
>>> ↪ Gaute Hope / mars 8, 2017 17:19:
>>>> You can also use `offlineimap -q` with higher number of `maxconnections` to get faster syncs. Together with https://github.com/gauteh/gmailieer and two IMAP accounts it takes me about 4 seconds to do a poll.
>>> 
>>> But isn't it good once in a while to run a real sync and not just a
>>> quick sync?
>>> 
>>> Maybe the poll.sh sample could increment the quick sync and after, n
>>> sync run a normal non quick sync. Does that look like a good idea? Even
>>> I could do that in bash I guess ;^)
>> 
>> Hey! I just added a small section on that in the wiki: https://github.com/astroidmail/astroid/wiki/Advanced-Polling-and-Processing-mail#advanced-polling
>> 
>> Could you have a look if that makes sense, please edit if it is unclear.
> 
> Your plan is to ruin by bash skills, isn't it? :)
> 
> It is very clear. Testing now :-)
> 

Sure! I did start before I got your email though :p

**Comment by gauteh** [comment]
I'm now at ~ 5 seconds for two IMAP accounts and one gmail account (using https://github.com/gauteh/gmailieer) for quick syncs with a fairly good internet connection. Only one of the IMAP servers allows more than one connection at the time. How about you?

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 9, 2017 9:20:
> I'm now at ~ 5 seconds for two IMAP accounts and one gmail account (using https://github.com/gauteh/gmailieer) for quick syncs with a fairly good internet connection. Only one of the IMAP servers allows more than one connection at the time. How about you?

1 second for 1 IMAP account with not many mailboxes :-)

Sometimes more though.

**Comment by gauteh** [comment]
Hugo Roy writes on mars 9, 2017 9:24:
> ↪ Gaute Hope / mars 9, 2017 9:20:
>> I'm now at ~ 5 seconds for two IMAP accounts and one gmail account (using https://github.com/gauteh/gmailieer) for quick syncs with a fairly good internet connection. Only one of the IMAP servers allows more than one connection at the time. How about you?
> 
> 1 second for 1 IMAP account with not many mailboxes :-)
> 

Yeah, think I'm at about 2 secs for the IMAP accounts alone.

**Comment by gauteh** [comment]
Gaute Hope writes on mars 9, 2017 9:30:
> Hugo Roy writes on mars 9, 2017 9:24:
>> ↪ Gaute Hope / mars 9, 2017 9:20:
>>> I'm now at ~ 5 seconds for two IMAP accounts and one gmail account (using https://github.com/gauteh/gmailieer) for quick syncs with a fairly good internet connection. Only one of the IMAP servers allows more than one connection at the time. How about you?
>> 
>> 1 second for 1 IMAP account with not many mailboxes :-)
>> 
> 
> Yeah, think I'm at about 2 secs for the IMAP accounts alone.
> 

Down to 2 secs when I run the gmail-sync in parallel. Pretty good. The
flags needed for external polling has been merged, they are documented
in the wiki. If someone wants set up a working example for using an IDLE
syncer please do that. I think we can probably close this bug for now?

**Comment by hugoroy** [comment]
Yes. This was not a bug any way. Just wanted to start the conversation ;-)
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gauteh** [comment]
Hugo Roy writes on mars 10, 2017 15:35:
> Yes. This was not a bug any way. Just wanted to start the conversation ;-)

Well, as a result I wrote gmailieer and I have cut my poll times from 70
secs to 2 secs so that's pretty good.

**Comment by jimcheetham** [comment]
Appreciate that this issue is closed, but I thought I'd add a comment anyway ...

I'm using a separate process to run fetchmail using --idle; but in common with other tools it doesn't seem to hook out to inform anyone that a message has been collected.
Instead, I've also set up an inotifywait condition on my Maildir that triggers notmuch new.

notmuch has hooks, and in the the post-new hook I'm tagging all the various types of email that comes in. I've added a pre-new hook script, that calls 'astroid --start-polling' and also preserves the 'notmuch count --lastmod' ID into a well-known $HOME/tmp file. In the post-new hook, I'm calling 'astroid --stop-polling' and 'astroid --refresh ID', getting the ID from that tmp file (and then removing it)

As a result, email is delivered to the IMAP server, fetchmail's --idle picks it up immediately and writes it to local disk, inotifywait detects the write and triggers notmuch; as soon as notmuch new has finished classifying the messages the astroid GUI is refreshed. This happens faster than my Android phone's Exchange connector sends a notification.

**Comment by jimcheetham** [comment]
Actually, I've just realised that astroid's polling can also call a script that will be able to monitor the fetchmail and inotifywait commands, to make sure that they are still running and restart them if they are not. I had been considering putting these components under runit or systemd, but they're much more closely related to the MUA than that (and can only be active when I'm logged in anyway, because $HOME is encrypted). So I'll have a think about that method now ...

**Comment by gauteh** [comment]
Jim Cheetham writes on mars 14, 2017 1:05:
> Actually, I've just realised that astroid's polling can also call a script that will be able to monitor the fetchmail and inotifywait commands, to make sure that they are still running and restart them if they are not. I had been considering putting these components under runit or systemd, but they're much more closely related to the MUA than that (and can only be active when I'm logged in anyway, because $HOME is encrypted). So I'll have a think about that method now ...
> 

Great! I'd be really interested in your setup, would it be possible to
set up an example in the wiki once you get it going properly?

The poll script runs at regular intervals and should return each time.
Astroid check for any changes to the database (difference in lastmod)
between start and stop of the poll script.

Note: --refresh should _not_ be called in connection with
--start-polling and --stop-polling. When you run --start-polling astroid
saves the current lastmod internally, and refreshes automatically
anything that changed between that and the next call to --stop-polling.

**Comment by jimcheetham** [comment]
https://github.com/astroidmail/astroid/wiki/Advanced-Polling-and-Processing-mail updated. Enjoy :-) I managed to re-engineer my whole workflow from scratch, it's far simpler, has fewer moving parts, doesn't use inotify, and is very quick. Basically, systemd --user runs fetchmail, fetchmail calls maildrop, maildrop calls notmuch, and notmuch notifies Astroid via its hooks.

**Comment by gauteh** [comment]
Jim Cheetham writes on mars 20, 2017 3:34:
> https://github.com/astroidmail/astroid/wiki/Advanced-Polling-and-Processing-mail updated. Enjoy :-) I managed to re-engineer my whole workflow from scratch, it's far simpler, has fewer moving parts, doesn't use inotify, and is very quick. Basically, systemd --user runs fetchmail, fetchmail calls maildrop, maildrop calls notmuch, and notmuch notifies Astroid via its hooks.
> 

Thanks, very through and very interesting! I might have to try something
similar.

I haven't figured out a way yet to use Gtk::Application without a X
server, since we really only need D-Bus I should think. If it is
possible maybe you can skip the DISPLAY dance.

The post-hook with a notmuch new lock-up might be a notmuch bug, I would
consider asking the notmuch folks if this is correct behavior. Are you
sure it just doesn't wait for a long time before it runs?

**Comment by gauteh** [comment]
Gaute Hope writes on mars 20, 2017 7:44:
> The post-hook with a notmuch new lock-up might be a notmuch bug, I would
> consider asking the notmuch folks if this is correct behavior. Are you
> sure it just doesn't wait for a long time before it runs?

You could also probably avoid the --start-polling --stop-polling by just
using --refresh at the end (with the revision from before poll as
argument). You can get the current revision by doing:

```
  $ notmuch count --lastmod * | cut -f3
```

**Comment by jimcheetham** [comment]
I'll have to check my setup, but I'm pretty sure I do have a DBus running when X is running - in any case, I can probably start one up easily enough. If the systemd --user fetchmail can see that bus by default, we're good; I'm still going to have to restart the fetchmail service from poll.sh but that's fine.

Using the lastmod with refresh might be a nicer way to cope with the occasional failures of notmuch; I like the spinner in the UI but I don't like it stuck 'on' :-) I could communicate the revision number via a named file or pipe, I may even be able to export it into the notmuch environment, which would be very neat. I'll have to do a bit of debug to see where the conflict is coming from in the first place though.

**Comment by gauteh** [comment]
Jim Cheetham writes on mars 20, 2017 7:57:
> I'll have to check my setup, but I'm pretty sure I do have a DBus running when X is running - in any case, I can probably start one up easily enough. If the systemd --user fetchmail can see that bus by default, we're good; I'm still going to have to restart the fetchmail service from poll.sh but that's fine.

Yeah, D-Bus must already be working since astroid is working with remote
instances. Ideally, it should work without the DISPLAY variable when
only doing remote commands.

> Using the lastmod with refresh might be a nicer way to cope with the occasional failures of notmuch; I like the spinner in the UI but I don't like it stuck 'on' :-) I could communicate the revision number via a named file or pipe, I may even be able to export it into the notmuch environment, which would be very neat. I'll have to do a bit of debug to see where the conflict is coming from in the first place though.
> 

Yeah - I agree, spinner is nice and astroid takes care of the revision,
but if you can't guarantee that --stop-polling is going to be called
you're going to be stuck with a spinner in 'on' now and then.
