### ISSUE TITLE
feature request: unread_all keybinding to mark all thread in index as read

### ISSUE THREAD

**Issue by TristanCacqueray** [astroidmail/astroid#318]
It would be convenient to be able to remove the unread tag from a thread index at once.

**Comment by mxmehl** [comment]
Just for the record: Currently, this needs 3 keystrokes: `T` (mark all threads), `+` (apply action to marked threads), `u` (mark unread)

**Comment by gauteh** [comment]
Hi, yes I think this is covered by the workflow described by Max. If you
just want to toggle unread of a thread in thread-index that is possible,
otherwise mark all messages and either toggle unread or use change
labels and '-unread'. Another approach is to refine the search and add
'tag:unread', mark all and toggle unread.

Regards, Gaute


Max writes on april 11, 2017 22:54:
