### ISSUE TITLE
Archiving message isn't working as intended

### ISSUE THREAD

**Issue by manishrjain** [astroidmail/astroid#396]
I have the following poll.sh script:

```
#! /bin/bash

if ! ping -w 1 -W 1 -c 1 mail.google.com; then
  echo "No internet connection"
  exit
fi

echo "Running imapfilter"
/usr/bin/imapfilter

echo "Retrieving mail"
/usr/bin/offlineimap

notmuch new

notmuch tag --batch <<EOF
  +work +inbox tag:new and folder:work/inbox
  +work -inbox +github tag:new and folder:work/github
  +personal +inbox tag:new and folder:personal/inbox
EOF
```

After I read a thread/message, pressing `a` shows the inbox tag as removed; but on the next poll, the messages shows up again in the inbox as `new, inbox`. So far, I haven't modified astroid's views, so I'm just using the default functionality (the only mod is the poll script).

Any ideas what's going on?

**Comment by gauteh** [comment]
Manish R Jain writes on september 7, 2017 2:34:
> I have the following poll.sh script:
> 
> ```
> #! /bin/bash
> 
> if ! ping -w 1 -W 1 -c 1 mail.google.com; then
>   echo "No internet connection"
>   exit
> fi
> 
> echo "Running imapfilter"
> /usr/bin/imapfilter
> 
> echo "Retrieving mail"
> /usr/bin/offlineimap
> 
> notmuch new
> 
> notmuch tag --batch <<EOF
>   +work +inbox tag:new and folder:work/inbox
>   +work -inbox +github tag:new and folder:work/github
>   +personal +inbox tag:new and folder:personal/inbox
> EOF
> ```
> 
> After I read a thread/message, pressing `a` shows the inbox tag as removed; but on the next poll, the messages shows up again in the inbox as `new, inbox`. So far, I haven't modified astroid's views, so I'm just using the default functionality (the only mod is the poll script).
> 
> Any ideas what's going on?

Are you removing the new tag from the messages? Otherwise they will be 
re-processed next time.

**Comment by manishrjain** [comment]
Yes, I removed the new tag -- I had done it elsewhere and forgot to update it here. Here's the updated poll.sh

```#! /bin/bash

if ! ping -w 1 -W 1 -c 1 mail.google.com; then
  echo "No internet connection"
  exit
fi

echo "Running imapfilter"
# /usr/bin/imapfilter

echo "Retrieving mail"
/usr/bin/offlineimap

notmuch new

notmuch tag --batch <<EOF
  +work +inbox tag:new and folder:work/inbox
  +work -inbox +github tag:new and folder:work/github
  +personal +inbox tag:new and folder:personal/inbox
  -new tag:new
EOF
```

But, this still doesn't do the sync from Astroid -> Gmail (via notmuch). I can see the inbox tag removed via astroid interface, but just somehow doesn't make it to Gmail. I have set notmuch sync flag to true.

**Comment by gauteh** [comment]
Manish R Jain writes on september 7, 2017 9:08:
> But, this still doesn't do the sync from Astroid -> Gmail (via notmuch). I can see the inbox tag removed via astroid interface, but just somehow doesn't make it to Gmail. I have set notmuch sync flag to true.
> 

Ah - that's a different story. Offlineimap only syncs maildir flags (or 
messages being moved around in the maildir mirroring the IMAP). Maildir 
flags are synced by notmuch between tags [0][1], but otherwise tags are 
not synced. I wrote `gmailieer` for syncing GMail tags with notmuch, it 
also fetches your emails - so it replaces offlineimap, and does fast 
syncs once you've done the initial sync: 
https://github.com/gauteh/gmailieer. It's getting fairly stable by now.

There's a bunch of info here on speeding up the polling: 
https://github.com/astroidmail/astroid/wiki/Advanced-Polling-and-Processing-mail#advanced-polling 
(feel free to improve the page, it's a bit hard to read the structure 
there now).


[0] https://notmuchmail.org/howto/#index3h2
[1] http://cr.yp.to/proto/maildir.html

**Comment by manishrjain** [comment]
Ah.. Ok. Would be good to put this in documentation -- that using offlineimap won't sync your changes back to Gmail.

I'll try out gmailieer. Thanks!

**Comment by gauteh** [comment]
Manish R Jain writes on september 7, 2017 9:29:
> Ah.. Ok. Would be good to put this in documentation -- that using offlineimap won't sync your changes back to Gmail.

Feel free ;) 

> 
> I'll try out gmailieer. Thanks!

Good luck!
