### ISSUE TITLE
astroid manpage

### ISSUE THREAD

**Issue by teto** [astroidmail/astroid#397]
Trying `man astroid` in nixos but doesn't work. As nixos derivations often forget to install man pages, I tried to fix it but can't find the man in the source so here is my question; does a manpage exist and if yes, where is it please ?

**Comment by gauteh** [comment]
Matthieu Coudron writes on september 7, 2017 6:27:
> Trying `man astroid` in nixos but doesn't work. As nixos derivations often forget to install man pages, I tried to fix it but can't find the man in the source so here is my question; does a manpage exist and if yes, where is it please ?

It does not exist. Yet.

**Comment by gauteh** [comment]
Fnux writes on July 24, 2018 9:26:
> I'm willing to help! Is it okay for you if I use [scdoc](https://drewdevault.com/2018/05/13/scdoc.html) to generate the man pages ? You can find an example [here](https://github.com/swaywm/sway/blob/master/sway/sway.1.scd).
> 

Great! That would be really good!

scdoc looks promising, but I am a bit concerned about its availabilitiy:
I just checked with Arch Linux and it is only available in AUR. How 
is its availabilitiy in other distros? If it is not available then it 
probably won't help on e.g. Debian?

**Comment by Fnux** [comment]
`scdoc` is already available (well, I packaged it) on Fedora: https://apps.fedoraproject.org/packages/scdoc

In order to be nice to distributions that do not package `scdoc` (yet), we can ship pre-generated manpages with the release archives. Manual pages are not considered as "precompiled binaries" :-)

Moreover, `scdoc` is super-easy to package: a simple C program without any external dependency.

**Comment by gauteh** [comment]
Fixed in #530.
