### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#406]
missing GMIME_DECRYPT_NONE and notmuch_database_get_default_indexopts:

```
$ scons -j 4
scons: Reading SConscript files ...
building version v0.6-329-ge5f2dc74 (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-3.0 >= 3.0.0... (cached) no
Checking for gmime-2.6 >= 2.6.18... (cached) yes
warning: gmime-2.6 will not be supported in the future.
Checking for webkitgtk-3.0... (cached) yes
Checking for vte-2.91... (cached) yes
Checking for C library libsass... (cached) no
Checking for C library libsass... (cached) yes
Checking for gobject-introspection-1.0... (cached) yes
Checking for libpeas-1.0... (cached) yes
Checking for C library notmuch... (cached) yes
Checking for C++ library boost_filesystem... (cached) yes
Checking for C++ library boost_system... (cached) yes
Checking for C++ library boost_program_options... (cached) yes
Checking for C++ library boost_log_setup... (cached) yes
Checking for C++ library boost_log... (cached) yes
Checking for C++ library boost_thread... (cached) yes
Checking for C++ library boost_date_time... (cached) yes
writing src/build_config.hh..

    debug   ..:  True
    release ..:  git
    version ..:  v0.6-329-ge5f2dc74
    profile ..:  False
    libsass ..:  True
    scss .....:  sassc ( use: False )
    plugins ..:  True
    terminal .:  True
    embedded .:  True
    gmime ....:  2.6
    prefix ...:  /usr/local

scons: done reading SConscript files.
scons: Building targets ...
compiling ==> src/crypto.cc
compiling ==> src/db.cc
compiling ==> src/modes/reply_message.cc
compiling ==> src/modes/saved_searches.cc
src/crypto.cc: In member function 'GMimeMessage* Astroid::Crypto::decrypt_message(GMimeMessage*)':
src/crypto.cc:136:79: error: 'GMIME_DECRYPT_NONE' was not declared in this scope
     GMimeDecryptResult * decrypt_res = g_mime_crypto_context_decrypt (gpgctx, GMIME_DECRYPT_NONE, NULL,
                                                                               ^~~~~~~~~~~~~~~~~~
src/db.cc: In member function 'Astroid::ustring Astroid::Db::add_message_with_tags(Astroid::ustring, std::vector<Glib::ustring>)':
src/db.cc:276:54: error: 'notmuch_database_get_default_indexopts' was not declared in this scope
         notmuch_database_get_default_indexopts (nm_db),
                                                      ^
src/db.cc:277:13: error: 'notmuch_database_index_file' was not declared in this scope
         &msg);
             ^
scons: *** [src/crypto.o] Error 1
scons: *** [src/db.o] Error 1
scons: building terminated because of errors.
```

**Comment by gauteh** [comment]
If you are using notmuch-git, please upgrade.

**Comment by gauteh** [comment]
And try latest astroid master for first error.

**Comment by jonassmedegaard** [comment]
I get that same last error (but not the first, as I compile against gmime 3.0).

I do *not* use notmuch-git but the package 0.25.1-1.

Seems commit 9c8a666 caused this. Is that commit crucial or can I safely revert it, until this gets solved?

**Comment by gauteh** [comment]
Jonas Smedegaard writes on september 23, 2017 9:45:
> I get that same last error (but not the first, as I compile against gmime 3.0).
> 
> I do *not* use notmuch-git but the package 0.25.1-1.
> 
> Seems commit 9c8a666 caused this. Is that commit crucial or can I safely revert it, until this gets solved?

Yes.

- gaute

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-09-23 09:55:47)
> Jonas Smedegaard writes on september 23, 2017 9:45:
> > I get that same last error (but not the first, as I compile against gmime 3.0).
> > 
> > I do *not* use notmuch-git but the package 0.25.1-1.
> > 
> > Seems commit 9c8a666 caused this. Is that commit crucial or can I safely revert it, until this gets solved?
> 
> Yes.

Uhm, yes crucial or yes safe to revert?


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on september 23, 2017 10:30:
> Quoting Gaute Hope (2017-09-23 09:55:47)
>> Jonas Smedegaard writes on september 23, 2017 9:45:
>> > I get that same last error (but not the first, as I compile against gmime 3.0).
>> > 
>> > I do *not* use notmuch-git but the package 0.25.1-1.
>> > 
>> > Seems commit 9c8a666 caused this. Is that commit crucial or can I safely revert it, until this gets solved?
>> 
>> Yes.
> 
> Uhm, yes crucial or yes safe to revert?
> 

safe to revert ;)

- gaute

**Comment by hugoroy** [comment]
FWIW, none of the AUR builds work for me :-)

**Comment by gauteh** [comment]
Hugo Roy writes on september 23, 2017 10:39:
> FWIW, none of the AUR builds work for me :-)

Need error message ? :)

**Comment by hugoroy** [comment]
Sorry :-) I added on the github interface so it probably didn't push by email!

Here it is again:

FWIW, none of the AUR builds work for me :-)

I get :

```
compiling ==> src/crypto.cc
compiling ==> src/db.cc
src/db.cc: In member function 'Astroid::ustring Astroid::Db::add_message_with_tags(Astroid::ustring, std::vector<Glib::ustring>)':
src/db.cc:276:9: error: 'notmuch_database_get_default_indexopts' was not declared in this scope
         notmuch_database_get_default_indexopts (nm_db),
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/db.cc:276:9: note: suggested alternative: 'notmuch_database_get_all_tags'
         notmuch_database_get_default_indexopts (nm_db),
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         notmuch_database_get_all_tags
src/db.cc:274:26: error: 'notmuch_database_index_file' was not declared in this scope
     notmuch_status_t s = notmuch_database_index_file (nm_db,
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/db.cc:274:26: note: suggested alternative: 'notmuch_database_mode_t'
     notmuch_status_t s = notmuch_database_index_file (nm_db,
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                          notmuch_database_mode_t
scons: *** [src/db.o] Error 1
scons: building terminated because of errors.
==> ERREUR : Une erreur s’est produite dans build().

```

**Comment by hugoroy** [comment]
Trying to install manually with scons following the README instructions gives this:

```
cons: Reading SConscript files ...
building version v0.10-4-g30a1e80c (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-3.0 >= 3.0.0... no
Checking for gmime-2.6 >= 2.6.18... yes
warning: gmime-2.6 will not be supported in the future.
Checking for webkitgtk-3.0... yes
Checking for vte-2.91... yes
Checking for C library libsass... no
Checking for C library libsass... yes
Checking for gobject-introspection-1.0... yes
Checking for libpeas-1.0... yes
Checking for C library notmuch... yes
Checking for C++ library boost_filesystem... no
boost_filesystem does not seem to be installed.

```

(I have boost and boost-libs on Arch and I used to compile astroid fine so I am wondering what's changed here)

**Comment by gauteh** [comment]
you can try to delete the .scons* dirs

**Comment by hugoroy** [comment]
Same result :-)

**Comment by gauteh** [comment]
added a test for n_d_index_file on latest master, should work without reverting commit 
now.

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-09-23 11:14:45)
> added a test for n_d_index_file on latest master, should work without reverting commit 
> now.

Thank was quick. Thanks!

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jonassmedegaard** [comment]
Quoting Gaute Hope (2017-09-23 11:14:45)
> added a test for n_d_index_file on latest master, should work without 
> reverting commit now.

Unfortunately your fix fails for me:

In file included from src/account_manager.cc:11:0:
src/db.hh:29:2: error: 'define' does not name a type; did you mean 'rewind'?
  define notmuch_database_index_file(d,f,o,m) notmuch_database_add_message(d,f,m)
  ^~~~~~
  rewind
src/account_manager.cc: In member function 'Astroid::Account* Astroid::AccountManager::get_assosciated_account(Glib::RefPtr<Astroid::Message>)':
src/account_manager.cc:132:10: error: aggregate 'Astroid::Db db' has incomplete type and cannot be defined
       Db db;
          ^~
src/account_manager.cc:135:25: error: invalid use of incomplete type 'class Astroid::NotmuchMessage'
           if (msg->nmmsg->in_query (&db, a.select_query)) {
                         ^~
In file included from src/astroid.hh:20:0,
                 from src/account_manager.cc:8:
src/proto.hh:17:9: note: forward declaration of 'class Astroid::NotmuchMessage'
   class NotmuchMessage;
         ^~~~~~~~~~~~~~
src/account_manager.cc:135:27: error: invalid use of incomplete type 'class Astroid::NotmuchMessage'
           if (msg->nmmsg->in_query (&db, a.select_query)) {
                           ^~~~~~~~
In file included from src/astroid.hh:20:0,
                 from src/account_manager.cc:8:
src/proto.hh:17:9: note: forward declaration of 'class Astroid::NotmuchMessage'
   class NotmuchMessage;
         ^~~~~~~~~~~~~~
g++ -o src/command_bar.o -c -pthread -DSASSCTX_CONTEXT_H -Wall -std=c++11 -pthread -DBOOST_LOG_DYN_LINK -g -Wextra -DDEBUG -D_LARGEFILE64_SOURCE -I/usr/include/gmime-3.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gobject-introspection-1.0 -I/usr/include/libpeas-1.0 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/vte-2.91 -I/usr/include/p11-kit-1 -Isrc src/command_bar.cc
scons: *** [src/account_manager.o] Error 1
In file included from src/astroid.cc:30:0:
src/db.hh:29:2: error: 'define' does not name a type; did you mean 'rewind'?
  define notmuch_database_index_file(d,f,o,m) notmuch_database_add_message(d,f,m)
  ^~~~~~
  rewind
src/astroid.cc: In member function 'int Astroid::Astroid::run(int, char**)':
src/astroid.cc:289:11: error: incomplete type 'Astroid::Db' used in nested name specifier
       Db::init ();
           ^~~~
src/astroid.cc: In member function 'void Astroid::Astroid::main_test()':
src/astroid.cc:348:9: error: incomplete type 'Astroid::Db' used in nested name specifier
     Db::init ();
         ^~~~
In file included from src/command_bar.cc:17:0:
src/db.hh:29:2: error: 'define' does not name a type; did you mean 'rewind'?
  define notmuch_database_index_file(d,f,o,m) notmuch_database_add_message(d,f,m)
  ^~~~~~
  rewind
src/command_bar.cc: In constructor 'Astroid::CommandBar::CommandBar()':
src/command_bar.cc:46:18: error: variable 'Astroid::Db db' has initializer but incomplete type
       Db db (Db::DbMode::DATABASE_READ_ONLY);
                  ^~~~~~
src/command_bar.cc:46:18: error: 'Astroid::Db::DbMode' has not been declared
src/command_bar.cc: In member function 'void Astroid::CommandBar::start_searching(Astroid::ustring)':
src/command_bar.cc:189:39: error: incomplete type 'Astroid::Db' used in nested name specifier
     search_completion->load_tags (Db::tags);
                                       ^~~~
src/command_bar.cc: In member function 'void Astroid::CommandBar::start_tagging(Astroid::ustring)':
src/command_bar.cc:212:36: error: incomplete type 'Astroid::Db' used in nested name specifier
     tag_completion->load_tags (Db::tags);
                                    ^~~~
src/command_bar.cc: In member function 'void Astroid::CommandBar::start_difftagging(Astroid::ustring)':
src/command_bar.cc:223:40: error: incomplete type 'Astroid::Db' used in nested name specifier
     difftag_completion->load_tags (Db::tags);
                                        ^~~~
scons: *** [src/astroid.o] Error 1
scons: *** [src/command_bar.o] Error 1
scons: building terminated because of errors.


-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by gauteh** [comment]
Jonas Smedegaard writes on september 23, 2017 11:39:
> Quoting Gaute Hope (2017-09-23 11:14:45)
>> added a test for n_d_index_file on latest master, should work without 
>> reverting commit now.
> 
> Unfortunately your fix fails for me:

ah, try latest again.

**Comment by jonassmedegaard** [comment]
Now fails differenty:

scons: *** [test/test_composed.passed] Error 1
test/test_open_db.cc: In member function 'void DbTest::open_error::test_method()':
test/test_open_db.cc:53:10: warning: variable 'db' set but not used [-Wunused-but-set-variable]
     Db * db;
          ^~
scons: building terminated because of errors.

**Comment by gauteh** [comment]
Thats just a warning in the tests

lør. 23. sep. 2017 kl. 13.59 skrev Jonas Smedegaard <
notifications@github.com>:

**Comment by hugoroy** [comment]
The astroid-git AUR build now gives this for me:

```
compiling ==> src/plugin/thread_view_activatable.c
compiling ==> src/plugin/gir_main.c
linking Program ==> girmain
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_get_width'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_get_height'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_device_set_thread_aware'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_egl_device_create'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_create_for_texture'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_glx_device_create'
collect2: error: ld returned 1 exit status
scons: *** [girmain] Error 1
scons: building terminated because of errors.
==> ERREUR : Une erreur s’est produite dans build().
    Abandon...
==> ERREUR : Makepkg n'a pas pu construire astroid-git.
```

So we're making progress :-D

**Comment by gauteh** [comment]
@hugoroy: you need to re-build webkitgtk, @mrvdb put up a pre-compiled binary here: https://mrblog.nl/files/2017/09/webkitgtk2-2.4.11-6-x86_64.pkg.tar.xz

**Comment by hugoroy** [comment]
↪ Gaute Hope / septembre 23, 2017 21:45:
> @hugoroy: you need to re-build webkitgtk, @mrvdb put up a pre-compiled binary here: https://mrblog.nl/files/2017/09/webkitgtk2-2.4.11-6-x86_64.pkg.tar.xz
> 

OK! it works :-)

Thanks!

**Comment by mxmehl** [comment]
I reinstalled `webkitgtk2` from the link but it didn't work for me. It seems, astroid requires `webkitgtk` (without the 2).

I found webkitgtk in my pacman cache ([download](https://up.mehl.mx/dl/webkitgtk-2.4.11-6-x86_64.pkg.tar.xz)) but it still fails with

```
linking Program ==> girmain
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_get_width'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_get_height'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_device_set_thread_aware'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_egl_device_create'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_gl_surface_create_for_texture'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/libwebkitgtk-3.0.so: undefined reference to `cairo_glx_device_create'
collect2: error: ld returned 1 exit status
scons: *** [girmain] Error 1
scons: building terminated because of errors.
```

For reference, here's my cached [webkitgtk2](https://up.mehl.mx/dl/webkitgtk2-2.4.11-6-x86_64.pkg.tar.xz).

Are these cached files any good? Or do I have to recompile them (which would take ages on my machine)

**Comment by gauteh** [comment]
@mxmehl this means that webkitgtk needs to be re-built. some libary webkitgtk depends on has changed.

**Comment by mxmehl** [comment]
Recompilation took around 8 hours, and finally the install worked. 

Maybe the compiled Arch Linux packages are helpful for others, too:

[webkitgtk 2.4.11-6](https://up.mehl.mx/dl/webkitgtk-2.4.11-6-x86_64.pkg.tar.xz) and [webkitgtk2 2.4.11-6](https://up.mehl.mx/dl/webkitgtk2-2.4.11-6-x86_64.pkg.tar.xz)

**Comment by gauteh** [comment]
Max writes on september 26, 2017 1:43:
> Recompilation took around 8 hours, and finally the install worked. 
> 
> Maybe the compiled Arch Linux packages are helpful for others, too:
> 
> [webkitgtk 2.4.11-6](https://up.mehl.mx/dl/webkitgtk-2.4.11-6-x86_64.pkg.tar.xz) and [webkitgtk2 2.4.11-6](https://up.mehl.mx/dl/webkitgtk2-2.4.11-6-x86_64.pkg.tar.xz)
> 

Great, could you update the wiki? https://github.com/astroidmail/astroid/wiki/Arch-Linux

**Comment by mxmehl** [comment]
> Great, could you update the wiki? https://github.com/astroidmail/astroid/wiki/Arch-Linux

Ah yes, sure. Done!

**Comment by gauteh** [comment]
Max writes on september 26, 2017 12:35:
>> Great, could you update the wiki? https://github.com/astroidmail/astroid/wiki/Arch-Linux
> 
> Ah yes, sure. Done!
> 

thanks, weird that the two webkitgtk2 package have different sha256 
sums. we can probably just remove the second one.

**Comment by MarcinWieczorek** [comment]
I have fixed the issue by adding `--enable-gl` flag to `cario` PKGBUILD.

**Comment by gauteh** [comment]
Great! Thanks!

**Comment by MarcinWieczorek** [comment]
Unfortunately they won't add that flag in the repo. Someone opened a bug report, a TU replied mentioning some post on the forums which the link to had expired. At the moment the astroid in AUR won't work without rebuilding that fairly big package.

**Comment by gauteh** [comment]
Marcin Wieczorek writes on oktober 12, 2017 21:08:
> Unfortunately they won't add that flag in the repo. Someone opened a bug report, a TU replied mentioning some post on the forums which the link to had expired. At the moment the astroid in AUR won't work without rebuilding that fairly big package.
> 

Ok, too bad. Or use the pre-built package in the wiki.

**Comment by MarcinWieczorek** [comment]
```plain
http://bin.marcin.co/cairo-1.15.8-2-x86_64.pkg.tar.xz
http://bin.marcin.co/cairo-1.15.8-2-x86_64.pkg.tar.xz.sig
```
Cairo with enabled gl
