### ISSUE TITLE
Segfault  when using second astroid instance ( using --help or --start-polling for example)

### ISSUE THREAD

**Issue by mrvdb** [astroidmail/astroid#454]
When a running instance of astroid is present and you invoke another one (typically on a fetch script which uses --start-polling / --stop-polling), the new instance crashes with a segfault.

The code causing it, is in the destructor:
```
Astroid::~Astroid () {
    if (accounts) delete accounts;

    if (m_config) delete m_config;

    if (poll) {
      poll->close ();
      delete poll;
    }

    if (actions) {
      actions->close ();
      delete actions;
    }
  }
````
All delete actions cause a segfault. Backtraces are not very useful so far, it's clear there is an interprocess conflict here. Perhaps look into using mutexes?

**Comment by gauteh** [comment]
The server instance (the first launched astroid instance) and the client 
instance run in different processes. I gather the segfault happens in 
the client instance.

These are different processes, and I don't think they can share mutexes, 
nor that it would do any good - since the two processes do not share 
Astroid instance. If the segfault is caused by the 
deletes', then commenting out the contents of the ~Astroid destructor 
should fix the segfault, can you confirm that?

The two processes share a reference to the Gtk::Application and can 
communicate by signals. 

The deletes' and ->close()'es do some cleaning up which normally are 
required - I haven't looked to closely now, but I don't think any of 
those (except config) are instantiated when run as a client, that is 
probably the cause of the segfault on delete. However, in that case the 
pointers *should* be NULL (C++ initializes to NULL by default..) and 
delete should not have been called..

**Comment by mrvdb** [comment]
> I gather the segfault happens in the client instance.

yes

**Comment by gauteh** [comment]
re pacman: well. good that it solved itself... re-open if it pops up again. weird...
