### ISSUE TITLE
Port to WebKit2/webkitgtk-4.0

### ISSUE THREAD

**Issue by ff2000** [astroidmail/astroid#49]
Do you plan to port astroid to WebKit2?
I could try it myself, but I have no idea about both WebKit1 and WebKit2 Apis. Do you have some hints where to start?

**Comment by gauteh** [comment]
ff2000 writes on January 10, 2016 8:36:
> Do you plan to port astroid to WebKit2?
> I could try it myself, but I have no idea about both WebKit1 and WebKit2 Apis Do you have some hints where to start?

I approve.

I actually tried this first, and I believe you can find my attempts in
the early git-history. But webkit2 is more separated and as far as I
could see we would not be able to access the DOM-tree as we do now, but
rather as a plugin.

It might actually work better to have some more separation between
astroid and the UI, as long as it can still be manipulated
programatically.

regards, gaute

**Comment by ff2000** [comment]
webkitgtk-2.10 comes with some webkitdom-headers, which look as if they allow modification of the dom-tree - isn't that enough?

Also I think I will wait with porting until 0.5 is released. I have never ever done GTK development (besides one hello world window some time ago), so I need some small issues for practising first ;)

**Comment by gauteh** [comment]
ff2000 writes on January 18, 2016 10:51:
> webkitgtk-2.10 comes with some webkitdom-headers, which look as if they allow modification of the dom-tree - isn't that enough?

Hopefully! Let's do some tests.
 
> Also I think I will wait with porting until 0.5 is released. I have never ever done GTK development (besides one hello world window some time ago), so I need some small issues for practising first ;)

#63 *hint* *hint*

**Comment by ff2000** [comment]
Excerpts from Gaute Hope's message of Januar 18, 2016 10:54 :
> ff2000 writes on January 18, 2016 10:51:
>> webkitgtk-2.10 comes with some webkitdom-headers, which look as if they allow modification of the dom-tree - isn't that enough?
> 
> Hopefully! Let's do some tests.
>  
>> Also I think I will wait with porting until 0.5 is released. I have never ever done GTK development (besides one hello world window some time ago), so I need some small issues for practising first ;)
> 
> #63 *hint* *hint*

Yay, that's what I planned ;)

**Comment by gauteh** [comment]
@emdete also mentioned https://github.com/litehtml

**Comment by mturquette** [comment]
Upvoting this issue: 👍 

Homebrew on macOS only supports newer webkitgtk:

```
$ brew info webkitgtk
webkitgtk: stable 2.10.9 (bottled)
Full-featured Gtk+ port of the WebKit rendering engine
http://webkitgtk.org
/usr/local/Cellar/webkitgtk/2.10.9_1 (331 files, 40.2M) *
  Poured from bottle on 2016-06-22 at 12:36:40
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/webkitgtk.rb
==> Dependencies
Build: xz ✔, cmake ✔
Required: gtk+3 ✔, libsoup ✔, enchant ✔, webp ✔
```

Two questions:
1. What version of webkitgtk does this translate to in GNU Linux/Debian packaging speak? I'm always confused by the package naming conventions... (see this stackoverflow [thread](http://stackoverflow.com/questions/19692818/webkitgtk-gtk2-gtk3))
2. Should the method for version checking webkitgtk in scons be updated to reflect the library name in macOS? See:

```
$ scons --prefix=/usr/local build
scons: Reading SConscript files ...
building version v0.5-228-g31ad8c35 (git)..
debug flag enabled: True
Checking for pkg-config... yes
Checking for gtkmm-3.0 >= 3.10... yes
Checking for glibmm-2.4... yes
Checking for gmime-2.6 >= 2.6.18... yes
Checking for webkitgtk-3.0... no
webkitgtk not found.
```

**Comment by gauteh** [comment]
Michael Turquette writes on juni 24, 2016 6:52:
> Upvoting this issue: 👍 
> 
> Homebrew on macOS only supports newer webkitgtk:
> 
> ```
> $ brew info webkitgtk
> webkitgtk: stable 2.10.9 (bottled)
> Full-featured Gtk+ port of the WebKit rendering engine
> http://webkitgtk.org
> /usr/local/Cellar/webkitgtk/2.10.9_1 (331 files, 40.2M) *
>   Poured from bottle on 2016-06-22 at 12:36:40
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/webkitgtk.rb
> ==> Dependencies
> Build: xz ✔, cmake ✔
> Required: gtk+3 ✔, libsoup ✔, enchant ✔, webp ✔
> ```
> 
> Two questions:
> 1. What version of webkitgtk does this translate to in GNU Linux/Debian packaging speak? I'm always confused by the package naming conventions... (see this stackoverflow [thread](http://stackoverflow.com/questions/19692818/webkitgtk-gtk2-gtk3))

I tried to get this running using homebrew at some point. I think the
last version of `webkitgtk` that works with `webkit1` is 2.4.11. 

> 2. Should the method for version checking webkitgtk in scons be updated to reflect the library name in macOS? See:
> 
> ```
> $ scons --prefix=/usr/local build
> scons: Reading SConscript files ...
> building version v0.5-228-g31ad8c35 (git)..
> debug flag enabled: True
> Checking for pkg-config... yes
> Checking for gtkmm-3.0 >= 3.10... yes
> Checking for glibmm-2.4... yes
> Checking for gmime-2.6 >= 2.6.18... yes
> Checking for webkitgtk-3.0... no
> webkitgtk not found.
> ```

No, because currently astroid needs webkitgtk, _not_ webkit2gtk. So the
check fails because brew-webkit is webkit2gtk (in the linux world, Arch
at least).


The main stopper when I initially tried to use webkit2 was the DOM
access methods, I think this is easier now. A lot of the other API is
very similar.

Regards, Gaute

**Comment by emdete** [comment]
another idea was to look at http://netsurf-browser.org/. out of security reasons i would not like to base on such complex systems as webkit or gecko to display simple things like emails. still others lack important features like JS or domtreechanges. but the guys are working on it. beside litehtml the netsurf seems to be a quite cool project. so instead investing into migration to webkit2 i would suggest to take a look into simple html render libraries.

**Comment by gauteh** [comment]
Can netsurf be embedded and used as GTK widget?

While I prefer a smaller / lightweight solution I am not necessarily
convinced it will be safer. 

It seems that several of the lightweight solutions are not completely
done yet, which is another point for using a more mainstream engine: it
is sure to get security updates, it is sure to be feature complete, and
it will remain an active project for the foreseeable future.

Given that manpower is a finite resource for both astroid and the webkit
projects - and web browsers are complex stuff - I am still leaning
towards webkit2 being the most pragmatic, and possible best,
alternative.

WebKit2 does have a DOM interface which matches the one from WebKit1,
this makes porint easy - except it is not accessible from the main
thread. A web extension must be written (this will run in the
webkit-process) which communicates with the astroid-process [0].

[0] https://blogs.igalia.com/carlosgc/2013/09/10/webkit2gtk-web-process-extensions/

**Comment by Ramblurr** [comment]
Any chance this will happen soon?

webkit 1 (aka the webkitgtk3 dependency in this project) is no longer maintained and has had over 200 security vulnerabilities. [source, see last section](https://blogs.gnome.org/mcatanzaro/2017/02/08/an-update-on-webkit-security-updates/)

Distributions will likely be removing it soon.

---
This week I found astroid mail, and made a pretty awesome isync/notmuch/msmtp/astroid setup. I also created a flatpak package for astroid (see #224), which is where I found out this project is using such an old an insecure webkit version.

As a result of this, I just can't use astroid yet, nor do I want to release my flatpak package until this fixed. (the flatpak package takes over 9hrs to compile because of webkit1).

astroid is a wicked cool MUA though. I wish I had time to help update it.

**Comment by Ramblurr** [comment]
I did some googleing, and I know next to nothing about the webkitgtk api. But from the resources below it looks like you can grab and manipulate the dom in webkit2.

- https://blogs.igalia.com/carlosgc/2013/09/10/webkit2gtk-web-process-extensions/
- https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebPage.html#webkit-web-page-get-dom-document
- https://webkitgtk.org/reference/webkitdomgtk/stable/WebKitDOMDocument.html

**Comment by gauteh** [comment]
Casey Link writes on september 16, 2017 16:49:
> I did some googleing, and I know next to nothing about the webkitgtk api. But from the resources below it looks like you can grab and manipulate the dom in webkit2.
> 
> - https://blogs.igalia.com/carlosgc/2013/09/10/webkit2gtk-web-process-extensions/
> - https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebPage.html#webkit-web-page-get-dom-document
> - https://webkitgtk.org/reference/webkitdomgtk/stable/WebKitDOMDocument.html
> 

The problem is that we need to use the new layout which requires us to:

* write a web-extension which manipulates the DOM tree (easy enough, the 
  API is almost identical).
* communication between the web-extension and the astroid process 
  (possibly using dbus) (cumbersome).

It is absolutely essential that we do move to webkit2 though to keep 
this project alive. See https://github.com/astroidmail/astroid/projects/1.

**Comment by Ramblurr** [comment]
Web extensions are written in Javascript, and sadly these days im more comfortable with JS than C.

I don't have something much extra time, but if it's straightforward I’d offer to help write the web extension bit. Where's the code that needs time be ported?

**Comment by gauteh** [comment]
Currently it's using the C API, which is located in thread_view.cc, let me
know if you have any questions! Great!

søn. 17. sep. 2017 kl. 09.44 skrev Casey Link <notifications@github.com>:

**Comment by gauteh** [comment]
Do you have any docs or examples I could have a look at on how that would work?

**Comment by Ramblurr** [comment]
Oops, there's been a misunderstanding on my part. I understood web extensions to mean [the new browser extension API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/What_are_WebExtensions) used by Chrome and Firefox.

But "web extensions" in the context of webkitgtk [are something else specific to gtk](https://blogs.igalia.com/carlosgc/2013/09/10/webkit2gtk-web-process-extensions/) and are definitely written in C, though they do support injecting JS into the browser context. 

So it doesn't look like I'll be helpful in this case :\

**Comment by gauteh** [comment]
Ok, too bad. I'll see if I can set up the framework for the new layout 
soon.

**Comment by gauteh** [comment]
Actually, it seems that we can run javascript without doing all the 
webextension stuff: 

  https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-web-view-run-javascript

In that case I'd be very much interested in your help.

**Comment by gauteh** [comment]
Gaute Hope writes on september 19, 2017 17:42:
> Actually, it seems that we can run javascript without doing all the 
> webextension stuff: 
> 
>   https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-web-view-run-javascript
> 
> In that case I'd be very much interested in your help.

The best would probably be to create a small JS library for manipulating 
the thread-view, and then interface with that (supplying new messages, 
changing state, etc..).

**Comment by Ramblurr** [comment]
Interesting!

Can you make a small writeup on what needs to be done in JS exactly? I'm not familiar with the codebase at all, but if you could provide a list of things that need to be done I could tackle those.

**Comment by gauteh** [comment]
Casey Link writes on september 20, 2017 9:23:
> Interesting!
> 
> Can you make a small writeup on what needs to be done in JS exactly? I'm not familiar with the codebase at all, but if you could provide a list of things that need to be done I could tackle those.

Yep! I started out, but I think this will change a bit as we go along. 
It would be great if we could get some basic functionality up and going 
(like showing messages) so that we can see if the design choice makes 
any sense.

Check out https://github.com/gauteh/astroid/tree/webkit2js (or #402). 
Expect this branch to be reset frequently. I've started to annotate the 
parts in thread_view.cc with `[JS]` and `[REIMPLEMENT]` to see which 
functions should go into the JS library. I created an almost empty file 
here: https://github.com/gauteh/astroid/blob/webkit2js/ui/thread-view.js 
where your code can go (not loading it at the moment). I don't have much 
experience with JS so don't hesitate to let me know if I'm doint stuff 
that does not make sense.

At first we need functionality to add messages, this will go something 
like:
* Create a copy of the email_div template in https://github.com/gauteh/astroid/blob/webkit2js/ui/thread-view.html
* Populate it with all the email content, this will provided through 
  arguments from the C++ code, would it be best to provide a structure 
  here? or just everything as arguments (author, tags, body content, 
  images)

Let's start with just basic information like: author, to, cc, bcc, tags, 
and regular text body. Later we need to add stuff like:

attachments, thumbnails (with img data provided as base64), encryption 
status etc. Perhaps it is easiest to create several functions for this 
so that we can do it incrementally, e.g.:

add_message(..)
add_encrypted_message (..)
add_attachment_to_message (..)

you can probably understand the DOM manipulation in thread_view.cc: https://github.com/gauteh/astroid/blob/webkit2js/src/modes/thread_view/thread_view.cc#L777

This is probably the most complex class in astroid, but I think it can 
be made significantly less so with this change.

Regards, Gaute

**Comment by gauteh** [comment]
Now loading javascript.

**Comment by gauteh** [comment]
There's some test code that runs some javascript code defined in the lib modifying the document: https://github.com/gauteh/astroid/blob/webkit2js/src/modes/thread_view/thread_view.cc#L629

**Comment by Ramblurr** [comment]
Great stuff. Will take this branch for a spin.

**Comment by gauteh** [comment]
#408

**Comment by mturquette** [comment]
I haven't had a chance to try and build on macOS yet. Has anyone else?

**Comment by gauteh** [comment]
@mturquette: Check out: https://github.com/astroidmail/homebrew-astroid for a version that works with astroid master and webkit1. I think @yeled might have tried to build using webkit2.

**Comment by c-alpha** [comment]
Just as if we needed even more incentives...
This just in:

> ------------------------------------------------------------------------
> WebKitGTK+ Security Advisory                               WSA-2017-0008
> ------------------------------------------------------------------------
> 
> Date reported      : October 18, 2017
> Advisory ID        : WSA-2017-0008
> Advisory URL       : https://webkitgtk.org/security/WSA-2017-0008.html
> CVE identifiers    : CVE-2017-7081, CVE-2017-7087, CVE-2017-7089,
>                     CVE-2017-7090, CVE-2017-7091, CVE-2017-7092,
>                     CVE-2017-7093, CVE-2017-7094, CVE-2017-7095,
>                     CVE-2017-7096, CVE-2017-7098, CVE-2017-7099,
>                     CVE-2017-7100, CVE-2017-7102, CVE-2017-7104,
>                     CVE-2017-7107, CVE-2017-7109, CVE-2017-7111,
>                     CVE-2017-7117, CVE-2017-7120, CVE-2017-7142.
> 
> Several vulnerabilities were discovered in WebKitGTK+.
> [...]

**Comment by gauteh** [comment]
Yeah, I doubt we are affected unless you view a HTML part - but definitely time to get to webkit2 as soon as possible.

**Comment by gauteh** [comment]
Downstream:
* https://bugzilla.redhat.com/show_bug.cgi?id=1438659

**Comment by gauteh** [comment]
Please see #455 for currently active solution to porting to webkit2. This uses C/C++ only by creating an webextension. Google Protobuf used for communication through unix domain sockets.
