### ISSUE TITLE
Import gpg keys

### ISSUE THREAD

**Issue by varac** [astroidmail/astroid#601]
Astroid should offer an option to directly import attached/inlie gpg keys into your gpg keyring.

**Comment by gauteh** [comment]
There are two ways in which you could achieve this now, either use a hook
(triggered by a key) or a plugin which pre-processes the message. If you
want to always extract the keys and import them use the process hook [0].
Otherwise to achieve a similar functionality as the links in your previous
issue use a keyboard hook which reads the email from the notmuch message id
and then imports it. It should be possible to do in a similar way with
either the Python Mail or GMime modules. If you use the process hook you
will have the keys before the message is validated, otherwise you need to
refresh the thread-view in order to have the new keys being taken into
account.

Note that you can also configure gnupg to automatically fetch keys for
signers.

[0] https://github.com/astroidmail/astroid/wiki/Plugins#astroidactivatable

**Comment by gauteh** [comment]
Closing this for now as it is possible with keyboard hooks.

**Comment by varac** [comment]
@gauteh Could you show/document an example how to setup a keyboard hook to import a gpg key please ?
